# docker-compose.yml - Para desarrollo local (opcional)

version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mean-mongodb-local
    environment:
      MONGO_INITDB_ROOT_USERNAME: meanadmin
      MONGO_INITDB_ROOT_PASSWORD: SecureP@ssw0rd123!
      MONGO_INITDB_DATABASE: meanapp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mean-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mean-nodejs-local
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://meanadmin:SecureP@ssw0rd123!@mongodb:27017/meanapp
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    depends_on:
      - mongodb
    networks:
      - mean-network

  nginx:
    image: nginx:alpine
    container_name: mean-nginx-local
    ports:
      - "80:80"
    volumes:
      - ./nginx-local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nodejs
    networks:
      - mean-network

volumes:
  mongodb_data:
  node_modules:

networks:
  mean-network:
    driver: bridge
